### ISSUE TITLE
Website shield does not redirect

### ISSUE THREAD

**Issue by eversiege** [coopbri/coopbri#1]
Clicking on "My website" will try to redirect but will be stuck on `about:blank` page. Tested with Vivaldi 6.2.3105.58 (Stable channel)

**Comment by coopbri** [comment]
Hey @eversiege, thank you for the report. I currently have my website down while revamping it, planning on getting it back up this week. I appreciate you taking time to report this!

**Comment by coopbri** [comment]
Website is now live. Cheers @eversiege :handshake:
